language: node_js
node_js:
- '5.0'
script:
- npm run build
deploy:
  provider: npm
  email: jimwhimpey@me.com
  api_key:
    secure: gAZXwQXzvok8dQmqI4qR+GGl58toLfIgT5JK5D3oKcNaVDYMWF6B2tKj5sEinebKYjQHlXhzu4GYfBoLA3Ur1f6pqhBpyMTS9dmJXW9N65DxCY2sIYQA4POUhkk3Ew7o9RWGhgWTZLqzAIdbYRTOtVulWMspKd1paarOQYmoB1n/GaqjHRfOqgwjAaAz5siDglcBxX96CGwsx2x1N/fnUQLni5or1kDAiykjdNdGaIwgETrHH57l3vaQkP3TZSTedjqPliGg0wYpVCJpraZ1sHlpcQrr4WWbCr5U44bspLrO2XMoUtYmnI5r7E83tNnLkJnDomjOOxLqCo5/T1oFX3CgB7qyIwpd1H+oJg/XrKfvujCW1RbNOgL5SlMWHeca9OJDMkfEdYTnfWWfpNc/59Fz28+RNZDAYPNq4ypf0HtQ7+34CtEPvE2YpFqz75fq7o1i+CK8xa5Tlhc05bVctZkzOaUNW64OM92jF/TY4dRGjPEkAA+HeZeVgUeWSpdKx3J1Lx21hJ7xvDf4HXD1rBUqR3uKWJ4R0vS7vwXSbNyJpUjEicqkdZGnSurr0M6C1vgUNF/e4AKhbYhjbNNcvRtH9sMB8Mczc2Qvtar1r3/OMJznxCBT9wliOyL6+7fuQdAIRLNOoVh95rpI5uyCPphLbaFLPBnD7oUcRoptq0k=
  on:
    tags: true
    repo: flickr/flickr-api-v1
